// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_URL       Type = 0
	Type_TCP       Type = 1
	Type_DNS       Type = 2
	Type_HOST_DOWN Type = 3
)

var Type_name = map[int32]string{
	0: "URL",
	1: "TCP",
	2: "DNS",
	3: "HOST_DOWN",
}

var Type_value = map[string]int32{
	"URL":       0,
	"TCP":       1,
	"DNS":       2,
	"HOST_DOWN": 3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Task struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Type     `protobuf:"varint,2,opt,name=type,proto3,enum=protos.Type" json:"type,omitempty"`
	Status               int64    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Context              string   `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Interval             int64    `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_URL
}

func (m *Task) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Task) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *Task) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type TaskListResponse struct {
	Code                 bool     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Tasks                []*Task  `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskListResponse) Reset()         { *m = TaskListResponse{} }
func (m *TaskListResponse) String() string { return proto.CompactTextString(m) }
func (*TaskListResponse) ProtoMessage()    {}
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *TaskListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListResponse.Unmarshal(m, b)
}
func (m *TaskListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListResponse.Marshal(b, m, deterministic)
}
func (m *TaskListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListResponse.Merge(m, src)
}
func (m *TaskListResponse) XXX_Size() int {
	return xxx_messageInfo_TaskListResponse.Size(m)
}
func (m *TaskListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListResponse proto.InternalMessageInfo

func (m *TaskListResponse) GetCode() bool {
	if m != nil {
		return m.Code
	}
	return false
}

func (m *TaskListResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type TaskResultRequest struct {
	TaskId               int32    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResultRequest) Reset()         { *m = TaskResultRequest{} }
func (m *TaskResultRequest) String() string { return proto.CompactTextString(m) }
func (*TaskResultRequest) ProtoMessage()    {}
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *TaskResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResultRequest.Unmarshal(m, b)
}
func (m *TaskResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResultRequest.Marshal(b, m, deterministic)
}
func (m *TaskResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResultRequest.Merge(m, src)
}
func (m *TaskResultRequest) XXX_Size() int {
	return xxx_messageInfo_TaskResultRequest.Size(m)
}
func (m *TaskResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResultRequest proto.InternalMessageInfo

func (m *TaskResultRequest) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type Metric struct {
	Metric               string            `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Value                float32           `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Step                 int64             `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StrategyId           int64             `protobuf:"varint,7,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *Metric) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Metric) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Metric) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Metric) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Metric) GetStrategyId() int64 {
	if m != nil {
		return m.StrategyId
	}
	return 0
}

type Metrics struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type TaskResultResponse struct {
	Code                 bool     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResultResponse) Reset()         { *m = TaskResultResponse{} }
func (m *TaskResultResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResultResponse) ProtoMessage()    {}
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *TaskResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResultResponse.Unmarshal(m, b)
}
func (m *TaskResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResultResponse.Marshal(b, m, deterministic)
}
func (m *TaskResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResultResponse.Merge(m, src)
}
func (m *TaskResultResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResultResponse.Size(m)
}
func (m *TaskResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResultResponse proto.InternalMessageInfo

func (m *TaskResultResponse) GetCode() bool {
	if m != nil {
		return m.Code
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protos.Type", Type_name, Type_value)
	proto.RegisterType((*Task)(nil), "protos.Task")
	proto.RegisterType((*TaskListResponse)(nil), "protos.TaskListResponse")
	proto.RegisterType((*TaskResultRequest)(nil), "protos.TaskResultRequest")
	proto.RegisterType((*Metric)(nil), "protos.Metric")
	proto.RegisterMapType((map[string]string)(nil), "protos.Metric.TagsEntry")
	proto.RegisterType((*Metrics)(nil), "protos.Metrics")
	proto.RegisterType((*TaskResultResponse)(nil), "protos.TaskResultResponse")
	proto.RegisterType((*Empty)(nil), "protos.Empty")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcd, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0xe3, 0x8f, 0xc4, 0xf5, 0xb4, 0x49, 0xfd, 0x8e, 0x5e, 0xc1, 0x62, 0x21, 0x11, 0xf9,
	0x64, 0xa1, 0x2a, 0x45, 0xed, 0x81, 0x8f, 0x0b, 0x07, 0x5a, 0x89, 0xa2, 0xd2, 0xa2, 0x4d, 0x10,
	0xc7, 0x6a, 0x1b, 0x2f, 0x91, 0x95, 0xc4, 0x36, 0x9e, 0x4d, 0x84, 0xef, 0x88, 0x1b, 0xff, 0x33,
	0xda, 0x5d, 0xbb, 0x4d, 0x0e, 0x9c, 0x3c, 0xcf, 0xce, 0x8c, 0xf7, 0xf9, 0x8d, 0xc7, 0x30, 0x24,
	0x59, 0x6f, 0xf3, 0xb9, 0x9c, 0x54, 0x75, 0xa9, 0x4a, 0x1c, 0x98, 0x07, 0xc5, 0xcf, 0x16, 0x65,
	0xb9, 0x58, 0xc9, 0x53, 0x23, 0xef, 0x37, 0xdf, 0x4f, 0x45, 0xd1, 0xd8, 0x92, 0xe4, 0xb7, 0x03,
	0xfe, 0x4c, 0xd0, 0x12, 0x47, 0xe0, 0xe6, 0x19, 0x73, 0xc6, 0x4e, 0xea, 0x71, 0x37, 0xcf, 0x70,
	0x0c, 0xbe, 0x6a, 0x2a, 0xc9, 0xdc, 0xb1, 0x93, 0x8e, 0xce, 0x8e, 0x6c, 0x39, 0x4d, 0x66, 0x4d,
	0x25, 0xb9, 0xc9, 0xe0, 0x13, 0x18, 0x90, 0x12, 0x6a, 0x43, 0xcc, 0x33, 0x5d, 0xad, 0x42, 0x06,
	0xc1, 0xbc, 0x2c, 0x94, 0xfc, 0xa9, 0x98, 0x3f, 0x76, 0xd2, 0x90, 0x77, 0x12, 0x63, 0x38, 0xc8,
	0x0b, 0x25, 0xeb, 0xad, 0x58, 0xb1, 0xbe, 0xe9, 0x79, 0xd0, 0xc9, 0x27, 0x88, 0xb4, 0x8f, 0xeb,
	0x9c, 0x14, 0x97, 0x54, 0x95, 0x05, 0x49, 0x44, 0xf0, 0xe7, 0x65, 0x26, 0x8d, 0xab, 0x03, 0x6e,
	0x62, 0x4c, 0xa0, 0xaf, 0x04, 0x2d, 0x89, 0xb9, 0x63, 0x2f, 0x3d, 0xdc, 0x31, 0x26, 0x68, 0xc9,
	0x6d, 0x2a, 0x39, 0x81, 0xff, 0x8c, 0x94, 0xb4, 0x59, 0x29, 0x2e, 0x7f, 0x6c, 0x24, 0x29, 0x7c,
	0x0a, 0x81, 0xce, 0xde, 0xb5, 0x94, 0x7d, 0x3e, 0xd0, 0xf2, 0x2a, 0x4b, 0x7e, 0xb9, 0x30, 0xf8,
	0x2c, 0x55, 0x9d, 0xcf, 0x35, 0xd2, 0xda, 0x44, 0xa6, 0x24, 0xe4, 0xad, 0xc2, 0xff, 0xa1, 0xbf,
	0x15, 0xab, 0x8d, 0x9d, 0x86, 0xcb, 0xad, 0xd0, 0xf6, 0xcc, 0x88, 0x3c, 0x53, 0x6b, 0x87, 0xf2,
	0x1c, 0x42, 0x95, 0xaf, 0x25, 0x29, 0xb1, 0xae, 0x0c, 0xbe, 0xc7, 0x1f, 0x0f, 0x74, 0x07, 0x29,
	0x59, 0xb5, 0xf0, 0x26, 0xc6, 0x13, 0xf0, 0x95, 0x58, 0x10, 0x1b, 0x18, 0x1e, 0xd6, 0xf1, 0x58,
	0x47, 0x93, 0x99, 0x58, 0xd0, 0x65, 0xa1, 0xea, 0x86, 0x9b, 0x2a, 0x7c, 0x01, 0x87, 0xa4, 0x6a,
	0xa1, 0xe4, 0xa2, 0xd1, 0x24, 0x81, 0x79, 0x11, 0x74, 0x47, 0x57, 0x59, 0xfc, 0x1a, 0xc2, 0x87,
	0x1e, 0x8c, 0xc0, 0x5b, 0xca, 0xa6, 0x85, 0xd1, 0xe1, 0x3e, 0x49, 0xd8, 0x92, 0xbc, 0x73, 0xdf,
	0x38, 0xc9, 0x39, 0x04, 0xf6, 0x4e, 0xc2, 0x14, 0x02, 0x0b, 0x4e, 0xcc, 0x31, 0xae, 0x46, 0xfb,
	0xae, 0x78, 0x97, 0x4e, 0x52, 0xc0, 0xdd, 0x49, 0xff, 0xfb, 0xbb, 0x25, 0x01, 0xf4, 0x2f, 0xd7,
	0x95, 0x6a, 0x5e, 0xbe, 0x02, 0x5f, 0x2f, 0x11, 0x06, 0xe0, 0x7d, 0xe5, 0xd7, 0x51, 0x4f, 0x07,
	0xb3, 0x0f, 0x5f, 0x22, 0x47, 0x07, 0x17, 0x37, 0xd3, 0xc8, 0xc5, 0x21, 0x84, 0x1f, 0x6f, 0xa7,
	0xb3, 0xbb, 0x8b, 0xdb, 0x6f, 0x37, 0x91, 0x77, 0xf6, 0xc7, 0x81, 0xe3, 0x69, 0x4b, 0x38, 0xb5,
	0x0b, 0x8e, 0x6f, 0xe1, 0x48, 0xaf, 0x4a, 0x77, 0x8c, 0xc3, 0xce, 0xa1, 0xb9, 0x24, 0x66, 0xbb,
	0x6b, 0xb1, 0xbb, 0x53, 0x49, 0x0f, 0xdf, 0xc3, 0x68, 0x2a, 0x8b, 0xec, 0xd1, 0x37, 0x1e, 0xef,
	0xe3, 0x51, 0x1c, 0xef, 0x6d, 0xd5, 0x1e, 0x5c, 0xd2, 0xbb, 0xb7, 0xbf, 0xd5, 0xf9, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x84, 0xc6, 0x21, 0xda, 0x6e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StrategyServiceClient is the client API for StrategyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StrategyServiceClient interface {
	ListStrategy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskListResponse, error)
	SendTaskResult(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*TaskResultResponse, error)
}

type strategyServiceClient struct {
	cc *grpc.ClientConn
}

func NewStrategyServiceClient(cc *grpc.ClientConn) StrategyServiceClient {
	return &strategyServiceClient{cc}
}

func (c *strategyServiceClient) ListStrategy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskListResponse, error) {
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, "/protos.StrategyService/ListStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) SendTaskResult(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*TaskResultResponse, error) {
	out := new(TaskResultResponse)
	err := c.cc.Invoke(ctx, "/protos.StrategyService/SendTaskResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyServiceServer is the server API for StrategyService service.
type StrategyServiceServer interface {
	ListStrategy(context.Context, *Empty) (*TaskListResponse, error)
	SendTaskResult(context.Context, *Metrics) (*TaskResultResponse, error)
}

// UnimplementedStrategyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStrategyServiceServer struct {
}

func (*UnimplementedStrategyServiceServer) ListStrategy(ctx context.Context, req *Empty) (*TaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStrategy not implemented")
}
func (*UnimplementedStrategyServiceServer) SendTaskResult(ctx context.Context, req *Metrics) (*TaskResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTaskResult not implemented")
}

func RegisterStrategyServiceServer(s *grpc.Server, srv StrategyServiceServer) {
	s.RegisterService(&_StrategyService_serviceDesc, srv)
}

func _StrategyService_ListStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).ListStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.StrategyService/ListStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).ListStrategy(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_SendTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).SendTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.StrategyService/SendTaskResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).SendTaskResult(ctx, req.(*Metrics))
	}
	return interceptor(ctx, in, info, handler)
}

var _StrategyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.StrategyService",
	HandlerType: (*StrategyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStrategy",
			Handler:    _StrategyService_ListStrategy_Handler,
		},
		{
			MethodName: "SendTaskResult",
			Handler:    _StrategyService_SendTaskResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
